apiVersion: v1
kind: Service
metadata:
  name: devhub-api-svc
  labels:
    app: devhub-api
spec:
  type: ClusterIP
  selector:
    app: devhub-api
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
